name: wise_words
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  delayed_display: ^2.0.0
  flutter_svg: ^2.0.9
  quiver: ^3.2.1
  flutter_launcher_icons: ^0.13.1
  csv: ^5.1.1
  clipboard: ^0.1.3 
  path_provider: ^2.1.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome.png
    - assets/images/heart.svg
    - assets/images/home.svg
    - assets/images/search.svg
    - assets/images/cog.svg
    - assets/images/share.svg
    - assets/images/filter.svg
    - assets/images/magnify.svg
    - assets/images/back.svg
    - assets/images/icon.png
    - assets/data/data_set_test copy.tsv
    - assets/data/data_set.tsv
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400